############# English navigation ##############

# main menu
[[main]]
name = "HOME"
url = "/"
weight = 1

[[main]]
name = "SPECIES"
url = "species/"
weight = 2


[[main]]
name = "GENES"
url = "genes/"
weight = 3


[[main]]
name = "FUNCTION"
url = "tags/"
weight = 4


[[main]]
name = "ABOUT"
url = "about/"
weight = 5







