############# English navigation ##############

# main menu
[[main]]
name = "HOME"
url = "/"
weight = 1

[[main]]
name = "SPECIES"
url = "authors/"
weight = 2


[[main]]
name = "GENES"
url = "elements/"
weight = 3


[[main]]
name = "FUNCTION"
url = "functions/"
weight = 4


[[main]]
name = "ABOUT"
url = "abouts/"
weight = 5







